import re

CHAIN_PHRASES = (
    "cult fit",
    "cult.fit",
    "gold s gym",
    "golds gym",
    "gold gym",
    "anytime fitness",
    "snap fitness",
    "fitness first",
    "planet fitness",
    "la fitness",
    "orangetheory",
    "orange theory",
    "equinox",
    "talwalkars",
    "talwalkar",
    "mcdonalds",
    "mcdonald",
    "burger king",
    "kfc",
    "subway",
    "dominos",
    "domino s",
    "pizza hut",
    "starbucks",
    "cafe coffee day",
    "costa coffee",
    "haldiram",
    "wow momo",
    "barbesque",
    "barbeque nation",
    "pvr",
    "inox",
    "apollo pharmacy",
    "medplus",
    "wellness forever",
    "lenskart",
    "titan eye",
    "nykaa",
    "reliance trends",
    "westside",
    "lifestyle store",
    "shoppers stop",
    "pantaloons",
    "max fashion",
    "hm ",
    "zara",
    "uniqlo",
    "ikea",
    "decathlon",
    "big bazaar",
    "dmart",
    "d mart",
    "more supermarket",
    "nature s basket",
    "walmart",
    "target",
    "costco",
    "7 eleven",
    "holiday inn",
    "marriott",
    "hilton",
    "hyatt",
    "taj hotel",
    "oberoi",
    "lemon tree",
    "oio rooms",
    "oyo rooms",
    "fabhotel",
    "treebo",
    "bluestone",
    "tanishq",
    "kalyan jewellers",
    "malabar gold",
    "jockey",
    "van heusen",
    "louis philippe",
    "allen solly",
    "peter england",
    "raymond",
    "lakme salon",
    "jawed habib",
    "naturals salon",
    "bblunt",
    "vlcc",
    "kaya clinic",
    "dr lal path",
    "thyroong",
    "srl diagnostics",
    "practo",
    "fortis",
    "apollo hospital",
    "max hospital",
    "manipal hospital",
    "aiims",
)


def is_chain(name):
    blob = f" {re.sub(r'[^a-z0-9.]+', ' ', str(name or '').lower())} "
    for phrase in CHAIN_PHRASES:
        if f" {phrase} " in blob or blob.strip() == phrase:
            return True
    return False
